apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapscale-consumer
spec:
  replicas: 2 # You can scale this up if the queue gets backed up
  selector:
    matchLabels:
      app: snapscale-consumer
  template:
    metadata:
      labels:
        app: snapscale-consumer
    spec:
      containers:
      - name: consumer
        image: himanshusarma123/snapscale-consumer:v1
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: DB_NAME
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: DB_PORT
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: AWS_REGION
          - name: AWS_SECRET_ACCESS_KEY
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: AWS_BUCKET_NAME
          - name: S3_DIRECTORY
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: S3_DIRECTORY
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: RABBITMQ_USER
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: RABBITMQ_PASSWORD
          - name: RABBITMQ_HOST
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: RABBITMQ_HOST
          - name: RABBITMQ_PORT
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: RABBITMQ_PORT
          - name: QUEUE_NAME
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: QUEUE_NAME