apiVersion: batch/v1
kind: Job
metadata:
  name: snapscale-db-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snapscale-db-init
  template:
    metadata:
      labels:
        app: snapscale-db-init
    spec:
      containers:
      - name: init-db
        image: himanshusarma123/database-init:v2
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: DB_PASSWORD
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: DB_PASSWORD
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: DB_NAME
  restartPolicy: OnFailure # REQUIRED for Jobs
backoffLimit: 4 # Number of retries before marking the job as failed