apiVersion: v1
kind: PersistentVolume
metadata:
  name: snapscale-static-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  # CRITICAL: This keeps the data safe if the PVC is deleted
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: "" # Leave empty for static binding
  awsElasticBlockStore:
    volumeID: "vol-0a3394321e794df4c" # YOUR VOLUME ID HERE
    fsType: ext4