apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapscale-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  # This forces the link to the PV above
  volumeName: snapscale-static-pv
  storageClassName: ""