apiVersion: batch/v1
kind: Job
metadata:
  name: snapscale-db-init
spec:
  # 'replicas' is NOT a field for Jobs. 
  # 'backoffLimit' must be indented here, under spec.
  backoffLimit: 4 
  template:
    metadata:
      labels:
        app: snapscale-db-init
    spec:
      containers:
      - name: init-db
        image: himanshusarma123/database-init:v2
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: DB_PASSWORD
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: snapscale-secrets
                key: DB_NAME
      # restartPolicy must be here, inside the Pod spec
      restartPolicy: OnFailure